excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - appnameTests
  - appnameUITests
  - Packages
disabled_rules: # rule identifiers to exclude from running
  - force_try
