branches:
  only:
    - master
    - develop
os:
  - linux
language: generic
sudo: required
dist: trusty
osx_image: xcode7.2
env:
  - SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2016-04-25-a
before_install:
  - git submodule init
  - git submodule update
install:
  - curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
script:
  - swift build
  - make
